blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Feature Request
    url: https://github.com/jedi-masters/go-toolkit/discussions/new?category%3AIdeas
    about: Share ideas for new features
  - name: â“ Ask a Question
    url: https://github.com/jedi-masters/go-toolkit/discussions/new
    about: Ask the community for help

